<?php

// fetchit7 content type names - used in node table "type" field, field instance "bundle" field
define("FETCHIT7_CONTENT_NAME_TABLE","fetchit7_content_table");
define("FETCHIT7_CONTENT_NAME_PARAM","fetchit7_content_param");

define("FETCHIT7_DBTYPE_NAME_PGSQL","postgresql");
define("FETCHIT7_DBTYPE_LABEL_PGSQL","PostgreSQL");
define("FETCHIT7_DBTYPE_NAME_MYSQL","mysql");
define("FETCHIT7_DBTYPE_LABEL_MYSQL","MySQL");
define("FETCHIT7_DBTYPE_NAME_MSSQL","sqlserver");
define("FETCHIT7_DBTYPE_LABEL_MSSQL","MS SQL Server");

