<?php

// fetchit7 content type names - used in node table "type" field, field instance "bundle" field
define("FETCHIT7_CONTENT_NAME_TABLE","fetchit7_content_table");
define("FETCHIT7_CONTENT_NAME_PARAM","fetchit7_content_param");

define("FETCHIT7_DBTYPE_NAME_PGSQL","postgresql");
define("FETCHIT7_DBTYPE_LABEL_PGSQL","PostgreSQL");
define("FETCHIT7_DBTYPE_NAME_MYSQL","mysql");
define("FETCHIT7_DBTYPE_LABEL_MYSQL","MySQL");
define("FETCHIT7_DBTYPE_NAME_MSSQL","sqlserver");
define("FETCHIT7_DBTYPE_LABEL_MSSQL","MS SQL Server");

define("FETCHIT7_CONTROLTYPE_NAME_TEXTBOX","textbox"); //define("F_DR_CONTROL_TEXTBOX",0);
define("FETCHIT7_CONTROLTYPE_NAME_DATESEL","date_select"); //define("F_DR_CONTROL_DATESEL",1);
define("FETCHIT7_CONTROLTYPE_NAME_DROPDOWN_SINGLE","dropdown_single"); //define("F_DR_CONTROL_DROPDOWN_SINGLE",2);
define("FETCHIT7_CONTROLTYPE_NAME_RADIOBTN","radio_buttons"); //define("F_DR_CONTROL_RADIOBTN",3);
define("FETCHIT7_CONTROLTYPE_NAME_CHECKBOXES","checkboxes"); //define("F_DR_CONTROL_CHECKBOXES",4);
define("FETCHIT7_CONTROLTYPE_NAME_DROPDOWN_MULTI","dropdown_multiple"); //define("F_DR_CONTROL_DROPDOWN_MULTI",5);
define("FETCHIT7_CONTROLTYPE_NAME_CHECKBOX","checkbox"); //define("F_DR_CONTROL_CHECKBOX",6);
define("FETCHIT7_CONTROLTYPE_NAME_DATETIMESEL","datetime_select"); //define("F_DR_CONTROL_DATETIMESEL",7);
define("FETCHIT7_CONTROLTYPE_NAME_POPUPDATE","date_popup"); //define("F_DR_CONTROL_POPUPDATE",8);

define("F_DR_TEXTBOX_TEXT",0);
define("F_DR_TEXTBOX_NUMBER",1);
define("F_DR_TEXTBOX_DATE",2);
