<?php

/**
 * @file
 * Lets drupal 7 site builders create forms and graphs connected to remote databases.
 * 
 * Creates custom content storing the form, graph and database connection metadata,
 * then uses that metadata to create the "connected" forms and graphs as menu callbacks
 * 
 */
 
 /**
  * Implementation of hook_menu
  */
function fetchit7_menu() {
	$items['admin/config/fetchit7'] = array(
		'title' => 'fetchit7',
		'description' => 'fetchit7 options',
		'position' => 'right',
		'weight' => -5,
		'page callback' => 'system_admin_menu_block_page',
		'access arguments' => array('administer site configuration'),
		'file' => 'system.admin.inc',
		'file path' => drupal_get_path('module', 'system'),
	);

	$items['admin/config/fetchit7/settings'] = array(
		'title' => 'fetchit7 settings',
		'description' => 'Change how the fetchit7 module operates',
		'position' => 'right',
		'weight' => -5,
		'page callback' => 'drupal_get_form',
		'page arguments' => array('fetchit7_admin_settings'),
		'access arguments' => array('administer site configuration'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'fetchit7.admin.inc',
		'file path' => drupal_get_path('module', 'fetchit7'),
	);

	$items['admin/config/fetchit7/reset'] = array(
		'title' => 'fetchit7 reset',
		'description' => 'Reset the fetchit7 data. (required after all fetchit7 data changes)',
		'position' => 'right',
		'weight' => -10,
		'page callback' => 'drupal_get_form',
		'page arguments' => array('fetchit7_admin_reset'),
		'access arguments' => array('administer site configuration'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'fetchit7.admin.inc',
		'file path' => drupal_get_path('module', 'fetchit7'),
	);

	return $items;
}
